name: Github Actions Typescript Standard
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          sudo chown -R $USER /usr/local
          npm uninstall typescript --no-save
          npm uninstall tslint --no-save
          npm install
          npm install -g codecov
          npm install -g request
      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORRECT_COVERAGE: ${{ secrets.CORRECT_COVERAGE }}
        run: |
          npm t
          codecov
          node request.js
      - name: Upstream to Standards
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ github.event_name == 'push'}}
        run: |
          ./upstream.sh
