name: Github Actions Typescript Standard
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  standard-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo chown -R $USER /usr/local
          npm uninstall typescript --no-save
          npm uninstall tslint --no-save
          npm install
          npm install -g codecov
          npm install -g request
      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORRECT_COVERAGE: ${{ secrets.CORRECT_COVERAGE }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm t
          codecov -f ./coverage/coverage-final.json
          node request.js
          ./upstream.sh
